import React from 'react';
import { Song, Track, Instrument } from 'reactronica';

import SheetMusic from './SheetMusic';

const SheetMusicSlide = () => {
  const [isPlaying, setIsPlaying] = React.useState();
  const [samplesLoaded, setSamplesLoaded] = React.useState(false);
  const [notes, setNotes] = React.useState();
  const handleEvent = React.useRef();
  const bpm = 80;

  handleEvent.current = event => {
    if (event && event.note && event.note !== 'z') {
      const { name, duration } = parseAbcNote(event.note);

      console.log(event.note, name, duration);

      setNotes([{ name, duration }]);
    }
  };

  return (
    <>
      <SheetMusic
        isPlaying={isPlaying}
        bpm={bpm}
        scale={2}
        tunebookString={`X:1\nM:4/4\nK:A\nL:1/4\n|:EA/c/BG/F/|Eec2|AG/B/EF|G2z2:|\n`}
        onEvent={handleEvent.current}
        onLineEnd={() => {
          setNotes([]);
        }}
      />

      <p style={{ fontSize: '0.6em' }}>
        Excerpt from Our Sailor Prince by J.C. Neild Jr, 1867, State Library of
        NSW.
        <br />
        <a href="https://collection.sl.nsw.gov.au/digital/file/06ddDNk67LV8G">
          collection.sl.nsw.gov.au/digital/file/06ddDNk67LV8G
        </a>
      </p>
      <p style={{ fontSize: '0.7em' }}>
        Sheet music generated by <a href="https://www.abcjs.net/">ABC JS</a>
      </p>

      <br />

      <button
        className="demoButton"
        disabled={!samplesLoaded}
        onClick={() => {
          setIsPlaying(!isPlaying);
        }}
      >
        {isPlaying ? 'Stop' : 'Play'}
      </button>

      <Song bpm={bpm}>
        <Track volume={-6}>
          <Instrument
            type="sampler"
            notes={notes}
            samples={{
              'C#3': `${process.env.PUBLIC_URL}/audio/piano/Player_dyn2_rr1_020_louder.wav`,
              'D#3': `${process.env.PUBLIC_URL}/audio/piano/Player_dyn2_rr1_022_louder.wav`,
              F3: `${process.env.PUBLIC_URL}/audio/piano/Player_dyn2_rr1_024_louder.wav`,
            }}
            onLoad={() => {
              setSamplesLoaded(true);
            }}
          ></Instrument>
        </Track>
      </Song>
    </>
  );
};

const parseAbcNote = abcNote => {
  let octave = 3;
  let duration;
  let noteName = abcNote.slice(0, 1);

  // Higher octave for lower case notes
  if (['c', 'd', 'e', 'f', 'g', 'a', 'b'].includes(noteName)) {
    octave = 4;
  }

  if (abcNote.includes('/')) {
    duration = '8n';
  } else {
    duration = '4n';
  }

  return {
    name: `${noteName}${octave}`,
    duration,
    octave,
  };
};

export default SheetMusicSlide;
